# Generated by Django 6.0.7 on 2026-07-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='join_button_text',
            field=models.CharField(blank=True, default='Join Today', max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='join_url',
            field=models.URLField(blank=True),
        ),
    ]
