# Generated by Django 6.0.7 on 2026-07-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_join_button_text_organization_join_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='join_url',
            field=models.CharField(blank=True),
        ),
    ]
