# Generated by Django 6.0.7 on 2026-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organization_join_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
    ]
