# Generated by Django 6.0.7 on 2026-07-25 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_hero_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='cards/')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('button_text', models.CharField(blank=True, max_length=200)),
                ('button_link', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.organization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
