# Generated by Django 6.0.7 on 2026-07-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_heroimage_order_alter_navigationitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
    ]
