# Generated by Django 6.0.7 on 2026-07-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_card_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='button_link',
            new_name='link',
        ),
    ]
