# Generated by Django 6.0.7 on 2026-07-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_button_link_card_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='button_text',
            new_name='link_text',
        ),
    ]
