# Generated by Django 6.0.7 on 2026-07-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_button_text_card_link_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='active',
            new_name='is_enabled',
        ),
        migrations.RenameField(
            model_name='heroimage',
            old_name='active',
            new_name='is_enabled',
        ),
        migrations.RenameField(
            model_name='navigationitem',
            old_name='enabled',
            new_name='is_enabled',
        ),
    ]
