# Generated by Django 6.0.7 on 2026-07-25 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_active_card_is_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='info_panels/')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('link_text', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_panels', to='core.organization')),
            ],
        ),
    ]
