# Generated by Django 6.0.7 on 2026-07-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_infopanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopanel',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
