# Generated by Django 6.0.7 on 2026-08-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_infopanel_is_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='infopanel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='organization',
            name='hero_button_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='welcome_button_text',
            field=models.CharField(default='Welcome Button Text', max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='welcome_button_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='welcome_description',
            field=models.TextField(blank=True, default='Welcome Description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='welcome_title',
            field=models.CharField(default='Welcome Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hero_button_text',
            field=models.CharField(blank=True, default='Hero Button Text', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hero_description',
            field=models.TextField(blank=True, default='Hero Description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hero_subtitle',
            field=models.CharField(default='Hero Subtitle', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hero_title',
            field=models.CharField(default='Hero Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='join_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='navigationitem',
            constraint=models.UniqueConstraint(fields=('organization', 'title'), name='unique_navigation_title_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='navigationitem',
            constraint=models.UniqueConstraint(fields=('organization', 'url'), name='unique_navigation_url_per_organization'),
        ),
    ]
