# Generated by Django 6.0.7 on 2026-08-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_heroimage_options_alter_infopanel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='hero_button_text',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='hero_button_url',
        ),
        migrations.AddField(
            model_name='organization',
            name='hero_primary_button_text',
            field=models.CharField(blank=True, default='Hero Primary Button Text', max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='hero_primary_button_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='hero_secondaru_button_text',
            field=models.CharField(blank=True, default='Hero Secondary Button Text', max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='hero_secondary_button_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
