# Generated by Django 6.0.7 on 2026-08-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_organization_hero_button_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='hero_secondaru_button_text',
            new_name='hero_secondary_button_text',
        ),
    ]
