# Generated by Django 6.1 on 2026-08-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_hero_secondaru_button_text_organization_hero_secondary_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='airport_icao',
            field=models.CharField(blank=True, help_text='ICAO airport identifier, e.g. KSNS', max_length=4),
        ),
    ]
