# Generated by Django 6.1 on 2026-08-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organization_airport_icao'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopanel',
            name='panel_type',
            field=models.CharField(choices=[('static', 'Static'), ('next_meeting', 'Next Meeting')], default='static', max_length=32),
        ),
    ]
