# Generated by Django 6.1 on 2026-09-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_convert_links_to_url_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='link',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='infopanel',
            name='link',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(help_text='Internal page: its URL name, e.g. "core:events". Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hero_primary_button_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hero_secondary_button_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='join_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='welcome_button_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
    ]
