# Generated by Django 6.1 on 2026-09-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_card_link_alter_infopanel_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopanel',
            name='link',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Off-site link: full address starting with "https://", "mailto:", or "tel:". Ignored for a "Next Meeting" panel - its link always points at whichever meeting is actually next.', max_length=200),
        ),
    ]
