# Generated by Django 6.1 on 2026-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-filled from the title if left blank. Link to this file from anywhere on the site with "resource:<slug>".', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='link',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Uploaded file: "resource:<slug>" (see Resources - each one shows its own slug to reuse here). Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='infopanel',
            name='link',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Uploaded file: "resource:<slug>" (see Resources - each one shows its own slug to reuse here). Off-site link: full address starting with "https://", "mailto:", or "tel:". Ignored for a "Next Meeting" panel - its link always points at whichever meeting is actually next.', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url',
            field=models.CharField(help_text='Internal page: its URL name, e.g. "core:events". Uploaded file: "resource:<slug>" (see Resources - each one shows its own slug to reuse here). Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hero_primary_button_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Uploaded file: "resource:<slug>" (see Resources - each one shows its own slug to reuse here). Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hero_secondary_button_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Uploaded file: "resource:<slug>" (see Resources - each one shows its own slug to reuse here). Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='join_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Uploaded file: "resource:<slug>" (see Resources - each one shows its own slug to reuse here). Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='welcome_button_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Uploaded file: "resource:<slug>" (see Resources - each one shows its own slug to reuse here). Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_resource_slug_per_organization'),
        ),
    ]
