# Generated by Django 6.1 on 2026-09-13 16:58

import core.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_resource_slug_alter_card_link_alter_infopanel_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - anyone'), ('members', 'Members - signed-in users only')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(storage=core.storage.private_storage, upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'rtf', 'txt', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to='core.organization')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(help_text="Delete or reassign this category's other resources before deleting it.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='core.resourcecategory'),
        ),
        migrations.AddConstraint(
            model_name='resourcecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'title'), name='unique_resource_category_title_per_organization'),
        ),
    ]
