# Generated by Django 6.1 on 2026-09-13 16:58

import shutil
from pathlib import Path

import core.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def move_existing_files_to_private_storage(apps, schema_editor):
    # The AlterField below switches Resource.file from the public
    # MEDIA_ROOT storage to private_storage (private_media/) - the
    # field's stored name (e.g. "resources/foo.pdf") doesn't change,
    # but which directory that name resolves against does. Without
    # this, any Resource row that already existed before this
    # migration keeps its physical file sitting under media/ while the
    # app now looks for it under private_media/, and resource_download
    # 500s trying to open a file that isn't there.
    Resource = apps.get_model("core", "Resource")
    media_root = Path(settings.MEDIA_ROOT)
    private_root = Path(settings.BASE_DIR) / "private_media"

    for resource in Resource.objects.exclude(file=""):
        old_path = media_root / resource.file.name
        new_path = private_root / resource.file.name
        if old_path.exists() and not new_path.exists():
            new_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(old_path), str(new_path))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_resource_slug_alter_card_link_alter_infopanel_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - anyone'), ('members', 'Members - signed-in users only')], default='public', max_length=16),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(storage=core.storage.private_storage, upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'rtf', 'txt', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to='core.organization')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(help_text="Delete or reassign this category's other resources before deleting it.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='core.resourcecategory'),
        ),
        migrations.AddConstraint(
            model_name='resourcecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'title'), name='unique_resource_category_title_per_organization'),
        ),
        migrations.RunPython(move_existing_files_to_private_storage, noop),
    ]
