# Generated by Django 6.1 on 2026-09-13 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_backfill_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(help_text="Delete or reassign this category's other resources before deleting it.", on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='core.resourcecategory'),
        ),
    ]
