# Generated by Django 6.1 on 2026-09-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_club_officers_resource_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='facebook_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Uploaded file: "resource:<slug>" (see Resources - each one shows its own slug to reuse here). Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_url',
            field=models.CharField(blank=True, help_text='Internal page: its URL name, e.g. "core:events". Uploaded file: "resource:<slug>" (see Resources - each one shows its own slug to reuse here). Off-site link: full address starting with "https://", "mailto:", or "tel:".', max_length=200),
        ),
    ]
