# Generated by Django 6.1 on 2026-09-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_organization_facebook_url_organization_instagram_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='hero_title',
        ),
    ]
