# Generated by Django 6.1 on 2026-09-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_organization_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopanel',
            name='image',
        ),
    ]
