# Generated by Django 6.1 on 2026-09-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_infopanel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='photo_credit',
            field=models.CharField(blank=True, help_text='Photographer name, shown as a small credit on the image.', max_length=200),
        ),
    ]
