# Generated by Django 6.1 on 2026-09-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_card_photo_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='photo_credit',
            field=models.CharField(blank=True, help_text='Small caption shown on the image, e.g. "Photo: Jasper Gray" or a placeholder reminder.', max_length=200),
        ),
    ]
