# Generated by Django 6.1 on 2026-09-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='welcome_background_credit',
            field=models.CharField(blank=True, help_text='Small caption shown on the background image, e.g. "Photo: Jasper Gray" or a placeholder reminder.', max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='welcome_background_image',
            field=models.ImageField(blank=True, upload_to='welcome/'),
        ),
    ]
