# Generated by Django 6.1 on 2026-09-16 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_organization_welcome_background_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='officers/')),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='core.organization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
