# Generated by Django 6.1 on 2026-09-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about_background_image',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
    ]
