# Generated by Django 6.1 on 2026-08-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Monthly Meeting', max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
    ]
