# Generated by Django 6.1 on 2026-08-12 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organization_airport_icao'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='organization',
            field=models.ForeignKey(default='90f5ee77-6ad3-4692-996b-3430ae1885e9', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.organization'),
            preserve_default=False,
        ),
    ]
