# Generated by Django 6.1 on 2026-09-13 02:30

import django.core.validators
import meetings.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_club_officers_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.FileField(blank=True, storage=meetings.storage.private_storage, upload_to='agendas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'rtf', 'txt'])]),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.FileField(blank=True, storage=meetings.storage.private_storage, upload_to='minutes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'rtf', 'txt'])]),
        ),
    ]
